version: '3'

services:
  learning-journey-front-end:
    build:
      context: /Users/ayilmaz/Desktop/GGProjects/examples/learning-journey
      dockerfile: Dockerfile
    volumes:
    - /Users/ayilmaz/Desktop/GGProjects/examples/learning-journey/:/app:delegated
    ports:
    - "3000:3000"
    networks:
    - learning-journey-network
    restart: always
  learning-journey-back-end:
    image:
    ports:
      - "3000:3000"
    networks:
      - learning-journey-network
    restart: always
networks:
  devops:
    driver: bridge
