apiVersion: v1
kind: Service
metadata:
  name: learning-journey-provider
  labels:
    app: learning-journey-provider
spec:
  type: NodePort
  ports:
  - name: '8080'
    port: 8080
    targetPort: 8080
  selector:
    app: learning-journey-provider